# fly.toml app configuration file generated for shop-api on 2024-10-22T09:49:42+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'shop-api'
primary_region = 'ams'

[build]

[env]
  PORT = '8080'

[http_service]
  internal_port = 4004
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
